public enum TraitID
{
    J_GREEDY_TRIBUTE,
    J_WITHERED_BLESSING,
    J_HEAVY_GUARD,
    J_BROKEN_FORCE,

    Q_ROYAL_TAX,
    Q_LIFE_LEECH,
    Q_SEAL_OF_SILENCE,
    Q_LONE_DUEL,

    K_ABSOLUTE_AUTHORITY,
    K_BLIND_FATE,
    K_ROYAL_DECREE,
    K_ENDLESS_WRATH,
    JOKER
}